title: "David Matias"
description: "Economics consultant | Energy & Environmental Economics"
markdown: kramdown
permalink: pretty

collections:
  electricity_posts:
    output: true
    permalink: /energy-markets/:name/
